// ─────────────────────────────────────────────────────────────────────────────
// Sub-Module 13 — Confirmation of Learning Questions
// Topic: Wave & Tidal Energy (slug: 'wave-tidal')
//
// Each question links to the most relevant section in SM13 for learners
// who want to review the material after an incorrect answer.
// ─────────────────────────────────────────────────────────────────────────────

import { ColQuestion } from './sm1-quiz'

export const sm13ColQuestions: ColQuestion[] = [
  {
    id: 'sm13-q1',
    question: 'What is the fundamental difference between wave energy and tidal energy?',
    options: [
      'Wave energy is generated offshore; tidal energy is always generated onshore',
      'Wave energy is driven by wind acting on the ocean surface; tidal energy is driven by the gravitational pull of the Moon and Sun',
      'Wave energy uses turbines; tidal energy uses floats and buoys',
      'Wave energy is predictable years in advance; tidal energy is highly variable and unpredictable',
    ],
    correctIndex: 1,
    explanation:
      'Wave energy originates from wind transferring energy to the ocean surface, creating oscillating waves whose power depends on wind speed, fetch, and duration. Tidal energy is driven by the gravitational interaction between Earth, the Moon, and the Sun, producing predictable rises and falls in sea level and tidal currents.',
    wrongExplanation:
      'The key distinction is the energy source: waves are generated by wind acting on the sea surface, while tides are caused by the gravitational pull of the Moon and Sun. This also means tidal energy is highly predictable, whereas wave energy varies with weather.',
    reviewSectionId: 'sm13-sec-1-intro',
    reviewSectionTitle: 'Introduction to Marine Energy',
  },
  {
    id: 'sm13-q2',
    question: 'Wave power per unit of wave crest width is primarily determined by which two wave characteristics?',
    options: [
      'Water temperature and salinity',
      'Wave height and wave period',
      'Ocean depth and seafloor geology',
      'Wind direction and coastal orientation',
    ],
    correctIndex: 1,
    explanation:
      'Wave power (in kW per metre of wave crest) is proportional to the square of the significant wave height and directly proportional to the wave period. Taller, slower waves carry considerably more energy than short, rapid ones — which is why the Atlantic coast of Europe has such high wave energy potential.',
    wrongExplanation:
      'Wave energy density is governed principally by wave height and wave period. Power scales with the square of wave height, so doubling wave height quadruples the available power — making these two parameters the most critical for resource assessment.',
    reviewSectionId: 'sm13-sec-2-physics',
    reviewSectionTitle: 'Physics of Wave & Tidal Energy',
  },
  {
    id: 'sm13-q3',
    question: 'Which of the following is NOT a recognised type of wave energy converter?',
    options: [
      'Oscillating Water Column (OWC)',
      'Point absorber',
      'Attenuator',
      'Tidal barrage',
      'Overtopping device',
    ],
    correctIndex: 3,
    explanation:
      'A tidal barrage is a tidal energy technology, not a wave energy converter. The main categories of wave energy converters are oscillating water columns (which compress air to drive a turbine), point absorbers (heaving buoys), attenuators (articulated structures aligned with wave direction), and overtopping devices (which fill a reservoir above sea level).',
    wrongExplanation:
      'A tidal barrage captures tidal flow across an estuary — it is a tidal technology, not a wave energy converter. Wave energy converters include oscillating water columns, point absorbers, attenuators, and overtopping devices.',
    reviewSectionId: 'sm13-sec-3-technologies',
    reviewSectionTitle: 'Marine Energy Technologies',
  },
  {
    id: 'sm13-q4',
    question: 'How does a tidal stream turbine differ from a tidal barrage?',
    options: [
      'Tidal stream turbines block an entire estuary to create a head of water; barrages use free-flowing current',
      'Tidal stream turbines generate power from free-flowing tidal currents like underwater wind turbines; barrages dam an estuary and use the water height difference to drive turbines',
      'Tidal stream turbines can only operate in freshwater rivers; barrages work in saltwater estuaries',
      'Tidal stream turbines require a minimum tidal range of 10 metres; barrages work with any tidal range',
    ],
    correctIndex: 1,
    explanation:
      'Tidal stream turbines are submerged devices placed in areas of fast tidal current and work analogously to wind turbines — they extract kinetic energy from moving water without impeding the flow significantly. Tidal barrages, by contrast, are large dams built across estuaries that trap water at high tide and release it through turbines, exploiting the potential energy of the tidal range.',
    wrongExplanation:
      'Tidal stream turbines harness the kinetic energy of flowing tidal currents — much like underwater wind turbines — with minimal environmental obstruction. Tidal barrages dam an entire estuary and use the height difference between high and low tide to generate power, which requires much larger civil engineering infrastructure.',
    reviewSectionId: 'sm13-sec-3-technologies',
    reviewSectionTitle: 'Marine Energy Technologies',
  },
  {
    id: 'sm13-q5',
    question: 'Where is the European Marine Energy Centre (EMEC) located, and what is its primary function?',
    options: [
      'Brest, France — it provides EU funding for offshore wind projects',
      'Lisbon, Portugal — it operates a wave energy test site in the Atlantic Ocean',
      'Orkney, Scotland — it provides accredited open-sea test facilities for wave and tidal energy devices',
      'Amsterdam, Netherlands — it certifies the structural safety of marine energy converters',
    ],
    correctIndex: 2,
    explanation:
      'EMEC is based in Orkney, Scotland, and operates the world\'s only purpose-built, accredited open-sea test and research centre for wave and tidal energy devices. Its location in the Pentland Firth and the Atlantic swell around Orkney offers some of the highest-quality marine energy resources in the world, making it the global benchmark for device testing.',
    wrongExplanation:
      'EMEC is located in Orkney, Scotland — not in any continental European country. It provides the world\'s leading open-sea testing infrastructure for wave and tidal technologies, benefiting from the exceptionally strong tidal streams of the Pentland Firth and Atlantic swells.',
    reviewSectionId: 'sm13-sec-3-technologies',
    reviewSectionTitle: 'Marine Energy Technologies',
  },
  {
    id: 'sm13-q6',
    question: 'The Orbital Marine O2 tidal turbine, commissioned in 2021, holds what distinction?',
    options: [
      'It is the world\'s deepest subsea tidal turbine, operating at 500 metres depth',
      'It is the world\'s largest operational tidal turbine, with a rated capacity of 2 MW',
      'It is the first tidal device to achieve grid parity without subsidy in the UK',
      'It is the first tidal turbine to operate in tropical waters',
    ],
    correctIndex: 1,
    explanation:
      'The Orbital Marine O2, deployed at EMEC in Orkney, is the world\'s most powerful tidal turbine with a rated capacity of 2 MW. Its twin 10-metre rotor blades extend on either side of a floating platform anchored to the seabed, and it has generated enough electricity to power over 2,000 UK homes.',
    wrongExplanation:
      'The Orbital O2 is notable for being the world\'s largest operational tidal turbine at 2 MW. It floats on the surface anchored by a mooring, with its twin rotors descending into the fast-flowing tidal stream below, and it has been tested at EMEC in Orkney.',
    reviewSectionId: 'sm13-sec-3-technologies',
    reviewSectionTitle: 'Marine Energy Technologies',
  },
  {
    id: 'sm13-q7',
    question: 'What is the commonly cited estimate for the commercially viable global tidal energy resource potential?',
    options: [
      'Around 80 TWh per year',
      'Around 800 TWh per year',
      'Around 8,000 TWh per year',
      'Around 80,000 TWh per year',
    ],
    correctIndex: 1,
    explanation:
      'Studies including those by the International Energy Agency estimate the commercially viable global tidal stream resource at approximately 800 TWh per year — roughly 3% of current global electricity consumption. The total theoretical resource is larger, but much of it is in locations too remote or with insufficient current speeds for economic exploitation.',
    wrongExplanation:
      'The commonly cited figure for commercially viable tidal resource potential is around 800 TWh per year. While the theoretical global tidal resource is much larger, this figure accounts for realistic site constraints including tidal current speeds, water depth, and grid access.',
    reviewSectionId: 'sm13-sec-2-physics',
    reviewSectionTitle: 'Physics of Wave & Tidal Energy',
  },
  {
    id: 'sm13-q8',
    question: 'Which combination of factors represents the most significant engineering challenges for marine energy devices?',
    options: [
      'Low water temperatures, low pressure at depth, and absence of sunlight',
      'Harsh storm conditions, saltwater corrosion, and biofouling from marine organisms',
      'High shipping traffic, noise pollution regulations, and planning permission delays',
      'Lack of suitable mooring materials and insufficient tidal current speeds in most locations',
    ],
    correctIndex: 1,
    explanation:
      'Marine energy devices must withstand extreme wave and storm forces, continuous exposure to saltwater which accelerates corrosion of metals and electrical systems, and biofouling — the attachment and growth of barnacles, mussels, and algae on submerged surfaces — which increases drag, reduces efficiency, and complicates maintenance.',
    wrongExplanation:
      'The toughest engineering challenges are the combination of storm-force loads, saltwater corrosion attacking structural and electrical components, and biofouling from marine organisms colonising submerged surfaces. Together these dramatically increase maintenance costs and reduce device availability.',
    reviewSectionId: 'sm13-sec-4-challenges',
    reviewSectionTitle: 'Challenges for Marine Energy',
  },
  {
    id: 'sm13-q9',
    question: 'Which environmental impact is of particular concern for tidal stream turbines in ecologically sensitive areas?',
    options: [
      'Significant alteration of global ocean currents',
      'Electromagnetic fields from power cables and noise during operation affecting marine mammals and fish',
      'Release of industrial chemicals used in turbine lubrication into the water column',
      'Complete blockage of fish migration routes similar to river dams',
    ],
    correctIndex: 1,
    explanation:
      'Tidal stream turbines produce low-frequency noise and electromagnetic fields from subsea power cables. These can affect the navigation, communication, and behaviour of marine mammals such as dolphins and porpoises, and may interfere with the electroreception used by sharks and rays. Ongoing research seeks to quantify and mitigate these effects.',
    wrongExplanation:
      'The key environmental concerns for tidal stream turbines are the noise generated during operation and electromagnetic fields emitted by subsea cables. Both can affect the sensory systems of marine mammals and elasmobranchs (sharks and rays), which is why ecological impact assessments are a core part of consenting for new marine energy projects.',
    reviewSectionId: 'sm13-sec-5-future',
    reviewSectionTitle: 'The Future of Marine Energy',
  },
  {
    id: 'sm13-q10',
    question: 'Why are hybrid marine energy systems — combining wave and/or tidal with other technologies — considered advantageous?',
    options: [
      'They eliminate the need for subsea power cables by storing energy on floating platforms',
      'Combining resources with different generation profiles increases overall capacity factor and reduces grid integration challenges',
      'They allow marine energy devices to operate in freshwater lakes, expanding the available resource',
      'Hybrid systems qualify for higher government subsidy rates in all major markets',
    ],
    correctIndex: 1,
    explanation:
      'Tidal energy is highly predictable but peaks at specific tidal phases, while wave energy varies with weather patterns. Combining these with offshore wind — which also varies — smooths overall output, increases the capacity factor of shared infrastructure such as cables and substations, and produces a more consistent power profile that is easier to integrate into electricity grids.',
    wrongExplanation:
      'Hybrid systems are valuable because wave, tidal, and wind resources have different but partially complementary generation profiles. By combining them on shared platforms or grid connections, developers can increase overall capacity factors and deliver a more consistent electricity output, reducing the storage and backup capacity required.',
    reviewSectionId: 'sm13-sec-5-future',
    reviewSectionTitle: 'The Future of Marine Energy',
  },
]
