// ─────────────────────────────────────────────────────────────────────────────
// Sub-Module 13: Wave & Tidal Energy
// Source: MOD1_SUB13_WAVE&TIDAL.pdf pages 4–38
//
// Phase 1 images served from /public/images/sm13/
// ─────────────────────────────────────────────────────────────────────────────

import type { SubModule, ImageAsset } from '@/types'
import {
  marineCapacityChart,
  marineResourceChart,
  tidalRegionsChart,
  marineLcoeChart,
} from './sm13-charts'

function p(key: string, text: string) {
  return {
    _type: 'block' as const, _key: key, style: 'normal' as const,
    children: [{ _type: 'span' as const, _key: `${key}s`, text, marks: [] as string[] }],
    markDefs: [] as never[],
  }
}
function h2(key: string, text: string) {
  return {
    _type: 'block' as const, _key: key, style: 'h2' as const,
    children: [{ _type: 'span' as const, _key: `${key}s`, text, marks: [] as string[] }],
    markDefs: [] as never[],
  }
}
function h3(key: string, text: string) {
  return {
    _type: 'block' as const, _key: key, style: 'h3' as const,
    children: [{ _type: 'span' as const, _key: `${key}s`, text, marks: [] as string[] }],
    markDefs: [] as never[],
  }
}
function bullet(key: string, text: string) {
  return {
    _type: 'block' as const, _key: key, style: 'normal' as const, listItem: 'bullet' as const, level: 1,
    children: [{ _type: 'span' as const, _key: `${key}s`, text, marks: [] as string[] }],
    markDefs: [] as never[],
  }
}
function localImage(filename: string, alt: string): ImageAsset {
  return { _type: 'image', asset: { _ref: `/images/sm13/${filename}`, _type: 'reference' }, alt, localSrc: `/images/sm13/${filename}` }
}

export const subModule13: SubModule = {
  _id: 'sm-13',
  title: 'SM 13 - Wave & Tidal Energy',
  slug: { _type: 'slug', current: 'wave-tidal' },
  orderIndex: 13,
  estimatedHours: 2,
  learningObjectives: [
    'Explain the fundamental physics governing wave energy and tidal energy generation',
    'Distinguish between wave energy, tidal stream energy, and tidal range energy',
    'Describe the main wave energy conversion technologies: point absorbers, attenuators, and oscillating water columns',
    'Explain how tidal stream turbines and tidal barrages convert tidal energy to electricity',
    'Assess the social, economic, and environmental challenges and opportunities of marine energy deployment',
    'Evaluate the global resource potential and current deployment landscape of wave and tidal energy',
    'Understand the future trajectory of marine energy costs and technology development',
  ],
  module: { _ref: 'module-1' },
  sections: [

    // ── SECTION 1: Introduction & History ─────────────────────────────────────
    {
      _id: 'sm13-sec-1-intro',
      title: 'Introduction to Wave & Tidal Energy',
      slug: { _type: 'slug', current: 'wave-tidal-introduction' },
      estimatedMinutes: 5,
      content: [
        {
          _type: 'imageBlock', _key: 'sm13-s1-hero',
          image: localImage('Images/AdobeStock_1106035761.webp', 'Wave energy device in the ocean'),
          fullWidth: true,
        },
        {
          _type: 'richText', _key: 'sm13-s1-text',
          content: [
            h2('sm13-s1-h1', 'What is Wave and Tidal Energy?'),
            p('sm13-s1-p1', 'Wave and tidal energy are two distinct but related forms of marine renewable energy. Both harness the power of the ocean -- one from the kinetic and potential energy of surface waves, the other from the gravitational forces governing the rise and fall of tides. Together with ocean thermal and salinity gradient energy, they form the "marine energy" sector.'),
            p('sm13-s1-p2', 'Tidal energy is a form of marine renewable energy that converts the kinetic energy of ocean tides -- caused by the gravitational interactions between the Earth, Moon, and Sun -- into electricity. Unlike wind and solar, tidal energy is highly predictable: tidal cycles can be forecast decades in advance with great precision, making it a uniquely reliable form of renewable energy.'),
            p('sm13-s1-p3', 'Wave energy captures the kinetic and potential energy of ocean surface waves. Waves are generated by wind blowing over the ocean surface, and in regions with consistent, high-energy wave conditions -- such as the western coasts of Europe, Australia, and the Americas -- the resource is vast and largely untapped. However, wave energy devices must withstand the extreme forces of the marine environment, which presents significant engineering challenges.'),
            h2('sm13-s1-h2', 'History of Marine Energy'),
            p('sm13-s1-p4', 'The idea of extracting energy from the ocean has existed for centuries. One of the earliest known applications dates back to the Middle Ages, with tidal mills -- simple but effective structures that used the ebb and flow of tides to grind grain. The world\'s first large-scale tidal barrage, the 240 MW La Rance Tidal Power Station in Brittany, France, became operational in 1966 and has been generating electricity reliably ever since.'),
            p('sm13-s1-p5', 'Modern wave and tidal energy technologies began to emerge in earnest in the 1970s, following the oil crisis. Several prototype technologies were developed -- including the Oscillating Water Column and early tidal turbines. Today, while still in the early stages of widespread commercial deployment, marine energy benefits from improved materials science, advanced digital modelling, and growing policy support.'),
          ],
        },
        marineResourceChart,
        tidalRegionsChart,
      ],
    },

    // ── SECTION 2: Wave & Tidal Energy Physics ────────────────────────────────
    {
      _id: 'sm13-sec-2-physics',
      title: 'The Physics of Wave & Tidal Energy',
      slug: { _type: 'slug', current: 'wave-tidal-physics' },
      estimatedMinutes: 10,
      content: [
        {
          _type: 'imageBlock', _key: 'sm13-s2-hero',
          image: localImage('Images/AdobeStock_1093830125.webp', 'Ocean waves showing energy potential'),
          fullWidth: true,
        },
        {
          _type: 'richText', _key: 'sm13-s2-text',
          content: [
            h2('sm13-s2-h1', 'Wave Energy Physics'),
            p('sm13-s2-p1', 'Wave energy refers to the process of harnessing the kinetic and potential energy contained in ocean surface waves. Once generated by wind, waves travel across the ocean in a rolling motion -- a combination of kinetic energy (from the movement of water particles) and potential energy (from the elevation of the wave surface). The power in a wave can be expressed mathematically using parameters such as wave height, wave period, and water density.'),
            p('sm13-s2-p2', 'Wave power is proportional to the square of wave height and to wave period. This means that doubling the wave height increases the wave\'s power by a factor of four. Regions with consistent, high-energy wave conditions -- such as the western coasts of Europe (the UK, Ireland, Portugal), Australia, and North America -- are ideal for wave energy extraction.'),
            h3('sm13-wave-types-h1', 'Types of Ocean Waves'),
            bullet('sm13-wave-types-b1', 'Wind-Generated Waves: The most common type of ocean wave, created by wind blowing across the sea surface. The size and energy of wind waves depends on wind speed, wind duration, and fetch — the distance over which wind acts on the water surface.'),
            bullet('sm13-wave-types-b2', 'Swell Waves: Generated by distant storms, swell waves travel long distances across the ocean and arrive at coastlines with considerable regularity and long wavelengths. This regularity makes them particularly valuable for wave energy generation, as energy output can be more predictable than for locally generated wind waves.'),
            bullet('sm13-wave-types-b3', 'Storm Waves: Highly energetic waves generated by nearby storm systems. While storm waves contain enormous energy, their unpredictability and extreme forces can pose challenges for wave energy device survivability and reliability.'),
            h2('sm13-s2-h2', 'Tidal Energy Physics'),
            p('sm13-s2-p3', 'Tidal energy harnesses the natural movement of ocean water caused by the gravitational interactions between the Earth, Moon, and Sun. As these celestial bodies shift in relation to one another, they generate regular and highly predictable changes in sea level -- the tides. There are two main forms of tidal energy:'),
            bullet('sm13-s2-b1', 'Tidal Range Energy: Captures the potential energy created by the difference in water height between high and low tides. It typically operates using a barrage (a dam-like structure) or tidal lagoon across an estuary or bay, using turbines to generate power as water flows in and out.'),
            bullet('sm13-s2-b2', 'Tidal Stream Energy: Captures the kinetic energy of fast-flowing tidal currents -- typically in narrow straits, around headlands, or in channels between islands where tidal flows are intensified. Tidal stream turbines look similar to underwater wind turbines.'),
            p('sm13-s2-p4', 'Tidal energy is particularly valued for its predictability. Unlike wind and solar power, tidal cycles can be forecast with high accuracy decades in advance. Tidal stream resources are strongest where geography accelerates tidal flows -- such as the Pentland Firth in Scotland, the Bay of Fundy in Canada, and the Raz Blanchard in France.'),
          ],
        },
        {
          _type: 'calloutBlock', _key: 'sm13-s2-callout',
          variant: 'info',
          title: 'Why Predictability Matters',
          body: 'Most renewable energy sources are variable -- wind blows inconsistently, and solar generates only during daylight. Tidal energy is the rare exception: tidal flows are governed by celestial mechanics and can be predicted with extraordinary precision years in advance. This predictability gives tidal energy a unique value in grid planning, allowing operators to schedule generation and balance supply and demand with confidence.',
        },
      ],
    },

    // ── SECTION 3: Conversion Technologies ───────────────────────────────────
    {
      _id: 'sm13-sec-3-technology',
      title: 'Wave & Tidal Conversion Technologies',
      slug: { _type: 'slug', current: 'wave-tidal-technology' },
      estimatedMinutes: 10,
      content: [
        {
          _type: 'imageBlock', _key: 'sm13-s3-hero',
          image: localImage('Images/AdobeStock_1124524277.webp', 'Tidal stream turbines underwater'),
          fullWidth: true,
        },
        {
          _type: 'richText', _key: 'sm13-s3-text',
          content: [
            h2('sm13-s3-h1', 'Wave Energy Conversion Technologies'),
            p('sm13-s3-p1', 'Several technologies have been developed to capture wave energy efficiently, each based on different physical principles:'),
            h3('sm13-s3-h2', 'Point Absorbers'),
            p('sm13-s3-p2', 'Point absorbers are buoy-like devices that bob up and down with the motion of waves. They capture energy from the relative motion between the floating body and a submerged reference structure. Point absorbers can capture wave energy from all directions and are relatively simple in concept, though the power take-off mechanisms -- converting mechanical motion to electricity -- are technically challenging.'),
            h3('sm13-s3-h3', 'Attenuators'),
            p('sm13-s3-p3', 'Attenuators are long, articulated floating structures aligned parallel to wave direction. They capture energy from the differential motion along their segments as waves pass underneath. Hydraulic or mechanical joints between segments convert this flexing motion into electricity. The Pelamis Wave Energy Converter was a pioneering attenuator design that reached sea trials off Portugal and Orkney before its development company ceased operations.'),
            h3('sm13-s3-h4', 'Oscillating Water Columns (OWC)'),
            p('sm13-s3-p4', 'OWC devices consist of a partially submerged chamber open to the sea. As waves enter the chamber, they compress the air above, which is forced through a turbine to generate electricity. As the wave recedes, air is drawn back through the turbine. The LIMPET plant on Islay, Scotland, was the world\'s first commercial wave power station using OWC technology.'),
            h2('sm13-s3-h5', 'Tidal Stream Conversion Technologies'),
            p('sm13-s3-p5', 'Tidal stream turbines extract kinetic energy from flowing tidal currents. They look and operate similarly to underwater wind turbines, with horizontal-axis turbines being the dominant design. Key characteristics include:'),
            bullet('sm13-s3-b1', 'Horizontal Axis Tidal Turbines (HATT): The most common design, with two or three blades rotating around a horizontal axis. The Orbital Marine O2 -- deployed in the Orkney Islands -- is one of the world\'s most powerful tidal stream devices at 2 MW.'),
            bullet('sm13-s3-b2', 'Variable Pitch Blades: Allow the turbine to maximise efficiency during both the ebb and flow of the tide, as the direction of current reverses.'),
            h2('sm13-s3-h6', 'Tidal Range: Barrages & Lagoons'),
            p('sm13-s3-p6', 'Tidal range energy captures the potential energy from the height difference between high and low tides, using large-scale infrastructure. Tidal barrages -- dam-like structures built across estuaries -- are the proven technology, exemplified by La Rance (France, 240 MW) and the Sihwa Lake station (South Korea, 254 MW). Tidal lagoons are an alternative design that impounds an area of sea rather than crossing an entire estuary, potentially with lower environmental impacts.'),
          ],
        },
        {
          _type: 'calloutBlock', _key: 'sm13-s3-callout',
          variant: 'info',
          title: 'The European Marine Energy Centre (EMEC)',
          body: 'The European Marine Energy Centre (EMEC) in Orkney, Scotland, is the world\'s leading marine energy test site. Since 2003, it has tested more wave and tidal devices than any other site in the world -- including devices from Atlantis Resources, Orbital Marine, Verdant Power, and many others. Its grid-connected test berths and world-class marine environment make it an irreplaceable asset for the global marine energy sector.',
        },
      ],
    },

    // ── SECTION 4: Challenges & Opportunities ─────────────────────────────────
    {
      _id: 'sm13-sec-4-challenges',
      title: 'Challenges & Opportunities',
      slug: { _type: 'slug', current: 'wave-tidal-challenges-opportunities' },
      estimatedMinutes: 10,
      content: [
        {
          _type: 'imageBlock', _key: 'sm13-s4-hero',
          image: localImage('Images/AdobeStock_157228356.webp', 'Marine energy development and coastal community'),
          fullWidth: true,
        },
        {
          _type: 'richText', _key: 'sm13-s4-text',
          content: [
            h2('sm13-s4-h1', 'Social Challenges'),
            bullet('sm13-s4-b1', 'Sea Use Conflicts: Marine environments are shared spaces -- fishing, shipping, recreation, and conservation all compete for the same waters as marine energy devices. Thorough stakeholder engagement and spatial planning are essential to avoid conflict.'),
            bullet('sm13-s4-b2', 'Procedural Equity: When local stakeholders are excluded from planning decisions, marine energy projects can face strong opposition. Inclusive, transparent processes build community acceptance.'),
            bullet('sm13-s4-b3', 'Cultural Impacts: In some coastal communities -- particularly those with indigenous connections to the sea -- marine energy development may affect cultural practices and heritage sites.'),
            h2('sm13-s4-h2', 'Economic Challenges'),
            bullet('sm13-s4-b4', 'High Capital Costs: Marine energy devices must withstand the extreme forces of the ocean environment -- requiring heavy-duty materials, specialised offshore installation vessels, and robust engineering. This results in high upfront costs compared to more mature renewables.'),
            bullet('sm13-s4-b5', 'Operations & Maintenance: Accessing and servicing underwater equipment requires specialised vessels, divers, or remotely operated vehicles. The harsh marine environment accelerates corrosion and biofouling.'),
            bullet('sm13-s4-b6', 'Grid Connection: Wave and tidal sites are often remote from existing grid infrastructure, requiring significant additional investment in subsea cables and onshore grid upgrades.'),
            h2('sm13-s4-h3', 'Environmental Challenges & Opportunities'),
            bullet('sm13-s4-b7', 'Marine Habitat Impact: Devices can disrupt seabed habitats during installation, and operating turbines carry some collision risk for marine animals. Careful site selection and monitoring are essential.'),
            bullet('sm13-s4-b8', 'Artificial Reef Effect: In practice, many marine energy structures provide new habitat for marine life -- functioning as artificial reefs that can increase biodiversity in the vicinity of devices.'),
            bullet('sm13-s4-b9', 'Zero Operational Emissions: Wave and tidal devices produce zero carbon emissions during operation. Over their lifetimes, they deliver highly favourable lifecycle carbon savings.'),
            bullet('sm13-env-noise', 'Underwater Noise Pollution: Construction activities such as pile driving and drilling generate high levels of underwater noise that can interfere with marine species\' communication, navigation, and behaviour. Marine mammals such as dolphins, porpoises, and whales that rely on echolocation are particularly sensitive. Cumulative noise impacts from multiple devices in a marine energy park can extend over significant distances.'),
            bullet('sm13-env-hydro', 'Hydrodynamic Alterations: Wave and tidal devices alter the hydrodynamic conditions of the surrounding water — affecting current speeds, sediment transport patterns, and water quality. Tidal barrages in particular can significantly alter estuarine ecosystems by changing tidal ranges upstream, affecting wetland habitats, fish spawning grounds, and nutrient exchange between rivers and the sea.'),
            h2('sm13-s4-h4', 'Social & Economic Opportunities'),
            bullet('sm13-s4-b10', 'Local Job Creation: Marine energy projects create skilled jobs in coastal communities -- engineering, fabrication, installation, and operations -- often in areas with few alternative employment opportunities.'),
            bullet('sm13-s4-b11', 'Energy Security for Islands & Remote Coasts: Wave and tidal systems are well-suited to providing reliable, locally generated electricity for island communities that currently depend on expensive diesel generation.'),
            bullet('sm13-s4-b12', 'Supply Chain Development: As the sector scales, it creates demand for fabrication, electrical services, logistics, and environmental consultancy -- stimulating broader economic activity in coastal regions.'),
          ],
        },
        marineCapacityChart,
      ],
    },

    // ── SECTION 5: The Future of Wave & Tidal Energy ──────────────────────────
    {
      _id: 'sm13-sec-5-future',
      title: 'The Future of Wave & Tidal Energy',
      slug: { _type: 'slug', current: 'wave-tidal-future' },
      estimatedMinutes: 5,
      content: [
        {
          _type: 'imageBlock', _key: 'sm13-s5-hero',
          image: localImage('Images/AdobeStock_1334418329.webp', 'Future of marine energy technology'),
          fullWidth: true,
        },
        {
          _type: 'richText', _key: 'sm13-s5-text',
          content: [
            h2('sm13-s5-h1', 'Technology Innovation & Cost Reduction'),
            p('sm13-s5-p1', 'Technological innovation is central to the advancement of marine energy. Key developments include advanced composite materials and anti-corrosion coatings that significantly increase device lifespans; advanced digital modelling for improved device design and site selection; and AI-driven control systems that maximise energy capture under varying sea conditions.'),
            p('sm13-s5-p2', 'Energy storage and grid integration are also key areas of innovation. As marine energy generation is predictable but time-varying (following tidal cycles), coupling with battery storage or hydrogen electrolysis can smooth output and maximise grid value. Hybrid systems combining tidal turbines with offshore wind or floating solar on a single platform offer further cost-sharing opportunities.'),
            h2('sm13-s5-h2', 'Hybrid Marine Energy Systems'),
            p('sm13-s5-p3', 'Hybrid marine energy systems integrate two or more renewable energy technologies -- typically wave, tidal, offshore wind, or solar -- into a single coordinated platform. By combining technologies with different output profiles, hybrid platforms can smooth energy output, better match grid demand, and share the cost of grid connection and offshore infrastructure.'),
            h2('sm13-s5-h3', 'The Future Trajectory'),
            p('sm13-s5-p4', 'The future of wave and tidal energy lies at the intersection of technological innovation, environmental responsibility, and global decarbonisation goals. While these marine energy sources are still emerging compared to wind and solar, their predictability and vast global resource potential make them highly valuable for balancing energy systems and enhancing grid stability as countries retire fossil fuel baseload generation.'),
            p('sm13-s5-p5', 'Wave and tidal energy represent powerful, predictable, and renewable sources of electricity with the potential to play a significant role in the global transition to clean energy. The challenge -- and the opportunity -- is to deploy this energy in a way that is sustainable, equitable, and accepted by local communities, while unlocking the economic benefits that the sector can bring to coastal regions worldwide.'),
          ],
        },
        marineLcoeChart,
        {
          _type: 'calloutBlock', _key: 'sm13-s5-callout',
          variant: 'key-fact',
          title: 'Marine Energy\'s Role in a Diversified Renewable Future',
          body: 'Wave and tidal energy will not replace wind and solar as the primary sources of clean electricity -- but they don\'t need to. Their real value lies in diversification: adding a reliable, predictable, low-carbon source that generates at different times and in different locations to wind and solar. A marine energy contribution of even 5-10% of global electricity by 2050 would represent a transformational achievement for the sector.',
        },
      ],
    },


    // ── SECTION 1b: History & Global Development ──────────────────────────────
    {
      _id: 'sm13-sec-1b-history',
      title: 'History & Global Development of Marine Energy',
      slug: { _type: 'slug', current: 'wave-tidal-history-global' },
      estimatedMinutes: 15,
      content: [
        {
          _type: 'imageBlock', _key: 'sm13-s1b-hero',
          image: localImage('Images/GLOBAL DEV.webp', 'Global development of marine energy around the world'),
          fullWidth: true,
        },
        {
          _type: 'richText', _key: 'sm13-s1b-text',
          content: [
            h2('sm13-s1b-h1', 'History of Marine Energy'),
            p('sm13-s1b-p1', 'The idea of extracting energy from the ocean has existed for centuries. One of the earliest known applications dates back to the Middle Ages, with the use of tidal mills -- simple but effective systems that harnessed the natural rise and fall of tides to turn waterwheels for grinding grain. These mills, often built into estuarine landscapes, represent some of the earliest recorded efforts to utilise marine forces for mechanical power.'),
            p('sm13-s1b-p2', 'The 20th century saw marine energy move from mechanical curiosity to electrical ambition. The world\'s first large-scale tidal barrage, the 240 MW La Rance Tidal Power Station in Brittany, France, became operational in 1966 and demonstrated the technical feasibility of using tidal range to produce electricity at scale. It remains operational today, proving that marine energy infrastructure can deliver electricity reliably over decades.'),
            p('sm13-s1b-p3', 'The 1973 oil crisis was a defining turning point for marine energy research. The sudden vulnerability of fossil fuel supply chains prompted governments and engineers to seriously explore alternative energy sources, including the ocean. Several prototype wave energy technologies emerged during this period -- including the Oscillating Water Column and the Salter\'s Duck, an innovative device designed to bob and rotate in response to wave motion. While many early devices faced setbacks due to technological immaturity and limited funding, this period established the conceptual and engineering foundations on which modern marine energy is built.'),
            p('sm13-s1b-p4', 'In the 21st century, marine energy has attracted growing policy support and private investment. The Pelamis Wave Energy Converter reached sea trials off Orkney, Scotland, and briefly off the coast of Portugal -- a genuine milestone for wave energy. In tidal stream energy, the Orbital Marine O2 device -- deployed in the Pentland Firth -- demonstrated 2 MW of capacity from a floating tidal turbine, setting a world record. The European Marine Energy Centre (EMEC) in Orkney, established in 2003, became the world\'s premier testing ground for wave and tidal technologies, hosting more marine energy devices than any comparable facility globally.'),
            h2('sm13-s1b-h2', 'Global Development of Wave and Tidal Energy'),
            p('sm13-s1b-p5', 'Europe has led global efforts in marine energy, particularly through the United Kingdom and France. The UK invested significantly through EMEC and the MeyGen tidal array project in the Pentland Firth, Scotland -- the world\'s largest multi-turbine tidal stream array in operation. France\'s La Rance Tidal Power Station, operational since 1966, remains a landmark proof-of-concept that has demonstrated the long-term viability of tidal range generation.'),
            h3('sm13-s1b-h3', 'Asia'),
            p('sm13-s1b-p6', 'South Korea has made substantial advances in tidal range energy, most notably with the Sihwa Lake Tidal Power Station -- the largest operational tidal plant in the world at 254 MW. The South Korean government has integrated tidal energy into broader coastal and environmental planning strategies. China is also expanding its marine energy ambitions, supporting wave and tidal trials along its eastern seaboard as part of its clean energy transition.'),
            h3('sm13-s1b-h4', 'North America'),
            p('sm13-s1b-p7', 'Canada has emerged as a leader in tidal stream development, leveraging the extraordinary tidal range of the Bay of Fundy in Nova Scotia -- one of the highest in the world. The FORCE (Fundy Ocean Research Center for Energy) initiative has positioned Canada at the cutting edge of tidal technology demonstration. The United States has focused on research and small-scale wave energy applications, including projects funded by the Department of Energy\'s Water Power Technologies Office.'),
            h3('sm13-s1b-h5', 'Other Regions'),
            bullet('sm13-s1b-b1', 'Portugal: Among the first nations to attempt commercial wave energy deployment with the Pelamis Wave Energy Converter, generating valuable performance and survivability data.'),
            bullet('sm13-s1b-b2', 'Australia: Continues to test a variety of wave technologies along its southwest coast, benefiting from world-class wave resources and government innovation programmes.'),
            bullet('sm13-s1b-b3', 'Global Trajectory: Today, development efforts are increasingly focused on reducing costs, improving reliability, and creating standardised frameworks to accelerate deployment. International collaboration and supportive policy environments remain critical to advancing marine energy as a credible contributor to the global energy mix.'),
          ],
        },
        {
          _type: 'calloutBlock', _key: 'sm13-s1b-callout',
          variant: 'key-fact',
          title: 'EMEC: The World\'s Marine Energy Test Centre',
          body: 'The European Marine Energy Centre (EMEC) in Orkney, Scotland, established in 2003, has tested more wave and tidal devices than any other facility in the world. Its grid-connected berths -- in real open-ocean conditions -- have been used by developers from across Europe, North America, and Asia. EMEC\'s role in de-risking marine technology has been central to accelerating the global development of the sector.',
        },
      ],
    },

    // ── SECTION 3b: Wave & Tidal Conversion Technologies (detailed) ───────────
    {
      _id: 'sm13-sec-3b-conversion',
      title: 'Wave & Tidal Conversion Technologies',
      slug: { _type: 'slug', current: 'wave-tidal-conversion-technologies' },
      estimatedMinutes: 30,
      content: [
        {
          _type: 'waveEnergyConversionDiagram' as const, _key: 'sm13-s3b-hero',
          title: 'Wave Energy Conversion Technologies',
        },
        {
          _type: 'richText', _key: 'sm13-s3b-text',
          content: [
            h2('sm13-s3b-h1', 'Wave Energy Conversion Technologies'),
            p('sm13-s3b-p1', 'Wave energy conversion involves transforming the kinetic and potential energy of ocean surface waves into usable electrical power. Several technologies have been developed to capture wave energy efficiently, each based on different physical principles and suited to varying marine environments. No single dominant technology has yet emerged -- instead, developers continue to optimise each design\'s power take-off (PTO) systems, mooring solutions, and structural adaptability.'),
            h3('sm13-s3b-h2', 'Point Absorbers'),
            p('sm13-s3b-p2', 'Point absorbers are floating devices that harness energy from the vertical motion of waves at a single point. These systems typically consist of a buoy connected to a fixed base or seabed anchor. As waves pass, the buoy moves up and down, activating a power take-off (PTO) system -- often hydraulic, pneumatic, or mechanical -- that converts this motion into electricity. Point absorbers are compact and can be deployed in arrays, making them suitable for nearshore and offshore installations. They can capture wave energy from all directions, giving them flexibility in varied sea conditions.'),
            h3('sm13-s3b-h3', 'Oscillating Water Columns (OWC)'),
            p('sm13-s3b-p3', 'OWC devices use the rise and fall of water within a partially submerged chamber to drive airflow. As waves enter and compress the air inside the chamber, the resulting pressure difference forces air through a bi-directional turbine, which spins regardless of airflow direction -- generating electricity as both the wave arrives and recedes. OWCs can be mounted on shorelines, breakwaters, or floating platforms, offering flexibility in deployment. Their design has minimal moving parts in the water, which helps reduce maintenance requirements. The LIMPET plant on Islay, Scotland, was the world\'s first commercial wave power station using OWC technology.'),
            h3('sm13-s3b-h4', 'Attenuators'),
            p('sm13-s3b-p4', 'Attenuators are long, articulated floating structures aligned parallel to wave direction. They capture energy from the differential motion along their segments as waves pass underneath. Hydraulic or mechanical joints between segments convert this flexing motion into electricity. Attenuators are especially effective in deep-water environments and are often used in offshore applications. The Pelamis Wave Energy Converter is the most well-known example of this technology, having undergone sea trials off Orkney and Portugal before its development company ceased operations -- leaving behind valuable technical data that continues to inform the field.'),
            h2('sm13-s3b-h5', 'Tidal Stream Conversion Technologies'),
            p('sm13-s3b-p5', 'Tidal stream energy conversion extracts kinetic energy from fast-moving tidal currents, typically in narrow straits or coastal channels where tidal flows are intensified. These technologies harness the horizontal movement of water rather than the vertical height difference exploited by tidal range systems. Tidal stream devices are often compared to underwater wind turbines, utilising the same core principles but operating in a denser and more predictable medium -- seawater.'),
            h3('sm13-s3b-h6', 'Horizontal-Axis Tidal Turbines (HATT)'),
            p('sm13-s3b-p6', 'Horizontal-axis tidal turbines are the most common design, resembling traditional wind turbines but mounted on the seabed or on floating platforms. They are aligned with the direction of tidal flow and generate electricity as moving water turns their blades. More advanced versions include dual-rotor systems, bi-directional turbines, and variable pitch blades to maximise efficiency during both ebb and flow tidal cycles. The Orbital Marine O2, deployed in the Pentland Firth, is one of the world\'s most powerful floating tidal stream devices at 2 MW.'),
            h3('sm13-s3b-h7', 'Vertical-Axis Tidal Turbines'),
            p('sm13-s3b-p7', 'Vertical-axis turbines are capable of harnessing tidal flows from any direction without needing alignment with the current. These are particularly useful in locations with turbulent or multi-directional currents. Other experimental devices include hydrofoils, oscillating hydrokinetic systems, and venturi-effect turbines, which focus and accelerate the flow to improve energy capture.'),
            h2('sm13-s3b-h8', 'Tidal Range: Barrages and Lagoons'),
            p('sm13-s3b-p8', 'Tidal range energy conversion captures the potential energy generated by the difference in height between high and low tides, typically using large-scale infrastructure. The most established method is the tidal barrage -- a dam-like structure built across an estuary or bay. As the tide rises, sluice gates are opened to allow water into a basin. When the tide outside falls, the water is released through low-head hydro turbines. La Rance in France (240 MW, operational since 1966) and the Sihwa Lake station in South Korea (254 MW) are the world\'s two largest operational tidal barrage facilities.'),
            h3('sm13-barrage-modes-h1', 'Tidal Barrage Operational Modes'),
            bullet('sm13-barrage-modes-b1', 'Single-Basin One-Way Generation: The simplest barrage configuration, where the basin fills during the incoming tide and turbines generate electricity only on the ebb (outgoing) tide. This produces electricity for approximately 6-8 hours per tidal cycle.'),
            bullet('sm13-barrage-modes-b2', 'Single-Basin Two-Way Generation: Turbines generate electricity on both the incoming and outgoing tides, effectively doubling the generation windows. However, two-way systems are more mechanically complex and the turbines must be capable of operating in both directions.'),
            bullet('sm13-barrage-modes-b3', 'Dual-Basin Systems: Two connected basins at different water levels allow for more continuous generation throughout the tidal cycle. One basin fills on the flood tide while the other empties on the ebb, with turbines operating between the two basins. This is the most complex configuration but can approach continuous generation.'),
            p('sm13-s3b-p9', 'A more recent concept, the tidal lagoon, creates an artificial embayment within the coastline that is sealed off to form a lagoon. This functions similarly to a barrage but with potentially lower ecological impact. Lagoons can be modular, scalable, and placed in areas with fewer environmental sensitivities than estuaries. The proposed Swansea Bay Tidal Lagoon in the UK, although not yet built, has become an important case study for this approach. Tidal range projects benefit from high predictability and long asset lifespans -- La Rance has been generating electricity for over 55 years.'),
            h2('sm13-s3b-h9', 'Hybrid Marine Energy Systems'),
            p('sm13-s3b-p10', 'Hybrid marine energy systems integrate two or more renewable energy technologies -- typically wave, tidal, offshore wind, or solar -- into a single, coordinated system. These systems aim to maximise energy capture, improve efficiency, and address the intermittency associated with individual renewable sources. Combining wave and tidal energy is particularly promising due to the complementary nature of their generation profiles and the shared use of offshore infrastructure.'),
            p('sm13-s3b-p11', 'The key advantage of hybrid systems lies in their ability to deliver greater consistency and reliability. Tidal energy is highly predictable and follows astronomical cycles; wave energy is more variable but often generates well when tidal output is lower, depending on weather conditions. By combining both, hybrid platforms can smooth out energy output and better match grid demand. Co-located devices -- such as tidal turbines placed on the seabed beneath floating wave energy converters -- allow shared foundations, cabling, and maintenance logistics, reducing overall costs.'),
            bullet('sm13-s3b-b1', 'Integration with Offshore Wind: Some hybrid platforms combine tidal turbines and offshore wind on a single structure, sharing grid connections and operational synergies.'),
            bullet('sm13-s3b-b2', 'Energy Storage Integration: Integrating battery storage or hydrogen production with hybrid marine systems further enhances grid stability and allows energy to be dispatched at high-value periods.'),
            bullet('sm13-s3b-b3', 'Test Projects: EMEC in Scotland and the Wave & Tidal Energy Test Site (WATTES) in South Korea have explored the potential of hybrid marine systems, validating the concept at scale.'),
          ],
        },
        {
          _type: 'tidalEnergyConversionDiagram' as const, _key: 'sm13-s3b-img2',
          title: 'Tidal Energy Conversion Technologies',
        },
        {
          _type: 'calloutBlock', _key: 'sm13-s3b-callout',
          variant: 'info',
          title: 'Why No Single Wave Technology Has Dominated',
          body: 'Unlike wind energy -- where horizontal-axis turbines became the clear dominant design -- wave energy has produced no single winning technology. The reason is the complexity and variability of wave motion itself: waves vary in height, period, direction, and depth in ways that favour different device designs in different locations. Point absorbers perform well in moderate offshore conditions; OWCs suit shoreline and breakwater deployment; attenuators are optimised for deeper, energetic seas. Future wave farms may deploy a combination of technologies tailored to local conditions.',
        },
      ],
    },

    // ── SECTION 4b: Opportunities in Marine Energy ────────────────────────────
    {
      _id: 'sm13-sec-4b-opportunities',
      title: 'Opportunities in Marine Energy',
      slug: { _type: 'slug', current: 'wave-tidal-opportunities' },
      estimatedMinutes: 15,
      content: [
        {
          _type: 'imageBlock', _key: 'sm13-s4b-hero',
          image: localImage('Images/SOCIAL OPPOR.webp', 'Coastal community benefiting from marine renewable energy'),
          fullWidth: true,
        },
        {
          _type: 'richText', _key: 'sm13-s4b-text',
          content: [
            h2('sm13-s4b-h1', 'Social Opportunities'),
            p('sm13-s4b-p1', 'Beyond the environmental and economic case, wave and tidal energy projects offer a range of meaningful social opportunities -- particularly for coastal, rural, and island communities that have historically faced energy insecurity and limited economic diversification. These social dimensions are increasingly central to how marine energy projects are planned and evaluated.'),
            p('sm13-s4b-p2', 'A key social opportunity is the potential to expand access to clean and reliable electricity, especially in remote or off-grid communities. Many coastal and island regions depend on expensive and polluting diesel generators for electricity. Wave and tidal systems, which are well-suited to localised deployment near coastlines, can provide a dependable local alternative -- supporting household energy use and critical services such as hospitals, schools, and water treatment facilities.'),
            bullet('sm13-s4b-b1', 'Island Energy Independence: Remote islands -- including communities in Scotland, the Pacific, and the Caribbean -- can use marine energy to reduce or eliminate diesel dependency, lowering costs and improving energy security.'),
            bullet('sm13-s4b-b2', 'Skills Development & Local Employment: The marine energy sector requires a skilled workforce ranging from marine engineers and data analysts to technicians and environmental scientists. Investments in local training programmes, apprenticeships, and partnerships with coastal educational institutions can build expertise and retain talent within communities, reducing outmigration.'),
            bullet('sm13-s4b-b3', 'Infrastructure Catalysts: Marine energy projects can catalyse infrastructure improvements -- upgraded ports, roads, and communication systems -- that benefit not just the energy sector but also fishing, tourism, and transportation industries.'),
            bullet('sm13-s4b-b4', 'Community Ownership & Governance: Community-led or co-owned marine energy projects have created pathways for local participation and empowerment, fostering trust and ensuring that the benefits of development are shared equitably. This is particularly important in areas with historic underinvestment.'),
            bullet('sm13-s4b-b5', 'Alignment with UN SDGs: Wave and tidal energy support SDG 7 (Affordable and Clean Energy), SDG 4 (Quality Education), SDG 8 (Decent Work and Economic Growth), and SDG 11 (Sustainable Cities and Communities).'),
            h2('sm13-s4b-h2', 'Economic Opportunities'),
            p('sm13-s4b-p3', 'Wave and tidal energy offer a range of economic opportunities that extend beyond clean electricity generation. As the sector matures, it presents pathways for job creation, regional economic development, industrial diversification, and export growth -- particularly for coastal and island nations seeking to transition to low-carbon economies.'),
            bullet('sm13-s4b-b6', 'Local Job Creation: Marine energy projects create diverse, skilled roles -- engineering, fabrication, installation, operations, and environmental services. These jobs are often in coastal areas with few alternative employment opportunities, including former shipbuilding or fishing hubs undergoing industrial transition.'),
            bullet('sm13-s4b-b7', 'Supply Chain Development: Projects stimulate local business opportunities across the supply chain -- from marine construction and vessel operation to port services, environmental consultancy, and specialised training. Where developers prioritise local procurement, this can contribute to the regeneration of coastal economies.'),
            bullet('sm13-s4b-b8', 'Industrial Diversification: Countries with existing strengths in offshore oil and gas, maritime engineering, or shipbuilding can leverage their infrastructure and expertise to support marine energy. This includes repurposing fabrication yards, vessels, and logistics bases, as well as retraining workers in a just transition from fossil fuel sectors.'),
            bullet('sm13-s4b-b9', 'Export Potential: Nations that establish early leadership in marine energy innovation -- such as the UK, Canada, or South Korea -- can benefit from exporting technologies, expertise, and services as global demand for ocean energy grows.'),
            bullet('sm13-s4b-b10', 'Energy Security & Price Stability: By harnessing predictable, locally generated energy, countries reduce dependence on imported fuels and exposure to volatile global energy markets -- particularly valuable for small island developing states (SIDS) and remote coastal communities.'),
            h2('sm13-s4b-h3', 'Environmental Opportunities'),
            p('sm13-s4b-p4', 'Wave and tidal energy offer significant environmental opportunities, particularly in the context of global efforts to combat climate change. As renewable, emissions-free sources of electricity, these technologies can reduce dependence on fossil fuels while also supporting marine conservation and climate resilience goals.'),
            bullet('sm13-s4b-b11', 'Zero Operational Emissions: Marine energy systems generate electricity without emitting carbon dioxide or other harmful pollutants. Their integration into national energy mixes helps countries meet climate targets under the Paris Agreement.'),
            bullet('sm13-s4b-b12', 'Predictability Advantage: Tidal cycles can be forecast with high accuracy years in advance -- unlike wind or solar. This makes tidal energy a valuable contributor to grid stability, reducing the need for fossil fuel backup generation.'),
            bullet('sm13-s4b-b13', 'Small Spatial Footprint: Marine energy devices avoid the land-use conflicts often associated with solar farms or wind turbines. Floating or submerged devices can be designed to coexist with marine conservation zones or other sustainable sea uses.'),
            bullet('sm13-s4b-b14', 'Artificial Reef Effect: Foundations and mooring systems may act as artificial reefs, providing new habitats for fish, shellfish, and other marine organisms, potentially increasing local biodiversity in the vicinity of devices.'),
            bullet('sm13-s4b-b15', 'Water Security Co-Benefits: Coupling marine energy with desalination or water purification systems can support local water security in coastal and island regions -- avoiding the high carbon footprint of conventional desalination methods.'),
          ],
        },
        {
          _type: 'marineEnergyOpportunitiesDiagram' as const, _key: 'sm13-s4b-img2',
          title: 'Marine Energy Opportunities',
        },
        {
          _type: 'calloutBlock', _key: 'sm13-s4b-callout',
          variant: 'key-fact',
          title: 'Marine Energy & the UN Sustainable Development Goals',
          body: 'Wave and tidal energy projects, when designed and delivered inclusively, can contribute to multiple UN Sustainable Development Goals simultaneously: SDG 7 (Affordable and Clean Energy) through local generation; SDG 8 (Decent Work) through coastal job creation; SDG 13 (Climate Action) through zero-emission electricity; and SDG 14 (Life Below Water) through careful environmental management and the potential for artificial reef co-benefits. This multi-dimensional value makes marine energy a compelling component of integrated sustainable development strategies for coastal regions.',
        },
      ],
    },

    // ── SECTION: Confirmation of Learning ────────────────────────────────────────
    // ── CONCLUSION: Sub-Module Summary ────────────────────────────────────────
    {
      _id: 'sm13-sec-conclusion',
      title: 'Sub-Module Summary',
      slug: { _type: 'slug', current: 'wave-tidal-summary' },
      estimatedMinutes: 5,
      content: [
        {
          _type: 'richText',
          _key: 'sm13-conc-text',
          content: [
            h2('sm13-conc-h1', 'Sub-Module Summary'),
            p('sm13-conc-p1', 'This sub-module has explored wave and tidal energy — the most predictable of all renewable energy sources. Unlike wind and solar, tidal flows are governed by gravitational forces and can be forecast decades in advance with near-perfect accuracy, making them uniquely valuable for grid planning and balancing. Wave energy, while less perfectly predictable, follows forecastable weather patterns and represents a vast, largely untapped global resource — particularly along high-latitude western coastlines where prevailing winds generate powerful, consistent swells.'),
            p('sm13-conc-p2', 'The technology landscape for marine energy is diverse and still maturing. Tidal stream turbines (led by Orbital Marine Power and Atlantis Resources) have demonstrated sustained grid-connected generation. Tidal range barrages (as at La Rance in France) and tidal lagoons offer large-scale, firm renewable power, though at significant capital cost and ecological sensitivity. Wave energy converters — including oscillating water columns, attenuators, and point absorbers — have proved harder to commercialise at scale due to the extreme marine environment and the diversity of device architectures. The European Marine Energy Centre (EMEC) in Orkney, Scotland, has been central to global testing and validation.'),
            p('sm13-conc-p3', 'Marine energy\'s primary challenge is cost reduction. Current generation costs are significantly above mature renewables, and the sector lacks the manufacturing scale and supply chain depth that has driven solar and wind costs down so dramatically. The pathway to competitiveness runs through standardisation, serial manufacturing, and aggregated project pipelines — mirroring the offshore wind journey from expensive pioneer projects in the 1990s to today\'s competitive industry. The UK, France, South Korea, Canada, and Australia are the leading national markets. With 2.4 billion people living within 100km of a coast, and growing political interest in diversifying the renewable energy mix, wave and tidal energy has a credible and important long-term role.'),
          ],
        },
        {
          _type: 'calloutBlock',
          _key: 'sm13-conc-callout',
          variant: 'key-fact',
          title: 'End of Sub-Module 13',
          body: 'You now have a comprehensive understanding of wave and tidal energy — the physics, the technology landscape, the challenges of commercialisation, and the unique value that highly predictable marine energy brings to a diversified renewable energy system.',
        },
      ],
    },
    {
      _id: 'sm13-sec-col',
      title: 'Confirmation of Learning',
      slug: { _type: 'slug', current: 'wave-tidal-confirmation' },
      estimatedMinutes: 15,
      content: [
        {
          _type: 'confirmationQuizBlock' as const,
          _key: 'sm13-col-quiz',
          subModuleSlug: 'wave-tidal',
          moduleId: 'module-1',
        },
      ],
    },

  ],
}
