// ─────────────────────────────────────────────────────────────────────────────
// Sub-Module 6: Onshore Wind
// Source: PDF pages 4–27 (verbatim text — do not edit without updating source)
//
// Phase 1 images are served from /public/images/sm6/
// Copy source files from: Platform_Dev/Module Assets/Sub-Module 6/Images/
// ─────────────────────────────────────────────────────────────────────────────

import type { SubModule, ImageAsset } from '@/types'
import {
  onshoreWindLcoeChart,
  onshoreWindCapacityChart,
  onshoreWindCountriesChart,
  onshoreWindForecastChart,
  onshoreWindRegionalInstallationsChart,
  onshoreWindLcoeRangeChart,
} from './sm6-charts'

// ── Portable Text block helpers ───────────────────────────────────────────────

function p(key: string, text: string) {
  return {
    _type: 'block' as const,
    _key: key,
    style: 'normal' as const,
    children: [{ _type: 'span' as const, _key: `${key}s`, text, marks: [] as string[] }],
    markDefs: [] as never[],
  }
}

function h2(key: string, text: string) {
  return {
    _type: 'block' as const,
    _key: key,
    style: 'h2' as const,
    children: [{ _type: 'span' as const, _key: `${key}s`, text, marks: [] as string[] }],
    markDefs: [] as never[],
  }
}

function h3(key: string, text: string) {
  return {
    _type: 'block' as const,
    _key: key,
    style: 'h3' as const,
    children: [{ _type: 'span' as const, _key: `${key}s`, text, marks: [] as string[] }],
    markDefs: [] as never[],
  }
}

function bullet(key: string, text: string) {
  return {
    _type: 'block' as const,
    _key: key,
    style: 'normal' as const,
    listItem: 'bullet' as const,
    level: 1,
    children: [{ _type: 'span' as const, _key: `${key}s`, text, marks: [] as string[] }],
    markDefs: [] as never[],
  }
}

// ── Image helper ──────────────────────────────────────────────────────────────

function localImage(filename: string, alt: string): ImageAsset {
  return {
    _type: 'image',
    asset: { _ref: `/images/sm6/${filename}`, _type: 'reference' },
    alt,
    localSrc: `/images/sm6/${filename}`,
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Sub-Module 6 Data
// ─────────────────────────────────────────────────────────────────────────────

export const subModule6: SubModule = {
  _id: 'sm-6',
  title: 'SM 6 — Onshore Wind',
  slug: { _type: 'slug', current: 'onshore-wind' },
  orderIndex: 6,
  estimatedHours: 2,
  learningObjectives: [
    'Understand the basic principles of how onshore wind turbines capture and convert wind energy',
    'Identify the key components of a wind turbine generator and describe their functions',
    'Trace the history of onshore wind from ancient windmills to modern multi-megawatt turbines',
    'Differentiate between Horizontal-Axis Wind Turbines (HAWTs) and Vertical-Axis Wind Turbines (VAWTs)',
    'Understand wind farm siting, layout optimisation, and grid integration considerations',
    'Assess the financial structure (DevEx, CapEx, OpEx, LCOE), policy frameworks, and social and environmental impacts of onshore wind',
  ],
  module: { _ref: 'module-1' },
  sections: [

    // ── SECTION 1: Introduction & Basic Principles (PDF pp. 4–6) ─────────────
    {
      _id: 'sm6-sec-1-intro',
      title: 'Introduction to Onshore Wind',
      slug: { _type: 'slug', current: 'onshore-wind-introduction' },
      estimatedMinutes: 10,
      content: [
        {
          _type: 'imageBlock',
          _key: 'sm6-s1-hero',
          image: localImage('Images/AdobeStock_1103617316.webp', 'Onshore wind farm at sunset'),
          fullWidth: true,
        },
        {
          _type: 'richText',
          _key: 'sm6-s1-text',
          content: [
            h2('sm6-s1-h1', 'The Basic Principles of Onshore Wind'),
            p('sm6-s1-p1', 'Wind energy is generated by harnessing the kinetic energy of moving air — a renewable resource available in virtually every country on earth. The core process involves three stages:'),
            bullet('sm6-s1-b1', 'Wind Kinetics: Wind flows over the land due to temperature and pressure differences, creating a renewable source of kinetic energy.'),
            bullet('sm6-s1-b2', 'Energy Conversion: Wind turbines convert this kinetic energy into mechanical energy, which is then transformed into electrical energy by a generator.'),
            bullet('sm6-s1-b3', 'Grid Integration: The electricity generated is transmitted to power grids for distribution to homes, businesses, and industries.'),
            p('sm6-s1-p2', 'Wind energy is a sustainable and cost-effective power source that significantly reduces greenhouse gas emissions and reliance on fossil fuels. It enhances energy security by diversifying energy sources and supports economic growth through job creation and local development, particularly in rural areas. As a clean energy solution, it minimises environmental impacts, producing no air or water pollution, while offering scalability to meet growing energy demands efficiently.'),
          ],
        },
        {
          _type: 'onshoreWindPrinciplesDiagram' as const,
          _key: 'sm6-s1-principles-diagram',
          title: 'How Onshore Wind Works — Step by Step',
          caption: 'The 12-step process from wind turning the blades through to electricity delivered via the national grid.',
        },
        {
          _type: 'richText',
          _key: 'sm6-s1-components',
          content: [
            h2('sm6-s1-h2', 'Key Components of a Wind Turbine Generator'),
            p('sm6-s1-p3', 'A Wind Turbine Generator is composed of many different components made of different materials that perform different roles to ensure the capture of wind and transfer of energy. While there are many of these components, there are a few key ones to be aware of:'),
            h3('sm6-s1-h3', 'Rotor Blades'),
            p('sm6-s1-p4', 'Capture the kinetic energy of the wind and convert it into rotational energy. The design and length of the blades directly affect the turbine\'s efficiency in harnessing wind energy.'),
            h3('sm6-s1-h4', 'Nacelle'),
            p('sm6-s1-p5', 'Houses the turbine\'s key mechanical and electrical components, including the gearbox, generator, and control systems. It serves as the operational core of the turbine.'),
            h3('sm6-s1-h5', 'Gearbox'),
            p('sm6-s1-p6', 'Increases the rotational speed from the blades (low-speed shaft) to the generator\'s required speed (high-speed shaft). This step-up in speed enables efficient electricity generation.'),
            h3('sm6-s1-h6', 'Generator'),
            p('sm6-s1-p7', 'Converts the mechanical energy from the rotating shaft into electrical energy, which can then be transmitted to the grid.'),
            h3('sm6-s1-h7', 'Tower'),
            p('sm6-s1-p8', 'Elevates the nacelle and blades to a height where wind speeds are stronger and more consistent. The tower\'s height improves energy capture and turbine efficiency.'),
            h3('sm6-s1-h8', 'Foundation'),
            p('sm6-s1-p9', 'Provides stability and anchors the turbine to the ground. It ensures the structure can withstand strong winds and other environmental stresses.'),
          ],
        },
      ],
    },

    // ── SECTION 2: Offshore vs Onshore & History (PDF pp. 7–12) ──────────────
    {
      _id: 'sm6-sec-2-history',
      title: 'History of Onshore Wind',
      slug: { _type: 'slug', current: 'onshore-wind-history' },
      estimatedMinutes: 15,
      content: [
        {
          _type: 'imageBlock',
          _key: 'sm6-s2-hero',
          image: localImage('Images/AdobeStock_274916580.webp', 'Historic windmill landscape'),
          fullWidth: true,
        },
        {
          _type: 'richText',
          _key: 'sm6-s2-offshore-compare',
          content: [
            h2('sm6-s2-h1', 'Comparing Offshore & Onshore Wind'),
            p('sm6-s2-p1', 'Onshore and offshore wind both harness the same fundamental resource — moving air — but differ significantly in their location, cost, scale, and engineering requirements. Offshore wind benefits from stronger and more consistent wind speeds at sea, but at higher capital cost. Onshore wind is more established, lower cost, and simpler to build and maintain, but may face greater planning constraints due to proximity to communities and landscapes.'),
          ],
        },
        {
          _type: 'offshoreVsOnshoreComparisonDiagram' as const,
          _key: 'sm6-s2-compare-diagram',
          title: 'Offshore vs Onshore Wind — Side-by-Side Comparison',
          caption: 'Offshore and onshore wind rated across four key attributes: wind availability, locations, turbine size, and community impact.',
        },
        {
          _type: 'richText',
          _key: 'sm6-s2-history',
          content: [
            h2('sm6-s2-h2', 'A History of Wind Power'),
            h3('sm6-s2-h3', 'Ancient Beginnings'),
            bullet('sm6-s2-b1', '200 BCE: The earliest recorded use of wind power occurs in Persia, where vertical-axis windmills are used to grind grain and pump water.'),
            h3('sm6-s2-h4', 'Middle Ages'),
            bullet('sm6-s2-b2', '11th Century: Horizontal-axis windmills emerge in Europe, primarily used for grinding grain and pumping water.'),
            bullet('sm6-s2-b3', '14th Century: Windmill designs are refined in the Netherlands, leading to the iconic Dutch windmills used for draining wetlands.'),
            h3('sm6-s2-h5', '19th Century: The Dawn of Modern Wind Power'),
            bullet('sm6-s2-b4', '1850s: The first wind-powered water pumps are developed in the United States, aiding agriculture in rural areas.'),
            bullet('sm6-s2-b5', '1887: James Blyth, a Scottish professor, builds the first wind turbine to generate electricity, powering his cottage.'),
            h3('sm6-s2-h6', 'Early 20th Century: Industrial Development'),
            bullet('sm6-s2-b6', '1903: Poul la Cour, a Danish scientist, constructs a wind turbine with aerodynamic blades, improving efficiency.'),
            bullet('sm6-s2-b7', '1920s: Small wind turbines gain popularity in rural America for charging batteries before grid electricity mainstreams.'),
            h3('sm6-s2-h7', 'Mid-20th Century Innovations'),
            bullet('sm6-s2-b8', '1931: The first large-scale wind turbine, the Balaclava windmill in the Soviet Union, produces 100 kW of electricity.'),
            bullet('sm6-s2-b9', '1941: The Smith-Putnam turbine, the first utility-scale wind turbine (1.25 MW), is installed in Vermont, USA, but only operates briefly.'),
            h3('sm6-s2-h8', '1970s: The Modern Wind Energy Era'),
            bullet('sm6-s2-b10', '1973: The oil crisis sparks renewed interest in renewable energy sources, including wind power.'),
            bullet('sm6-s2-b11', '1978: Denmark pioneers the use of modern wind turbines for electricity generation, supported by government incentives.'),
            h3('sm6-s2-h9', '1980s: Commercialisation'),
            bullet('sm6-s2-b12', '1980: The first utility-scale wind farm is commissioned in New Hampshire, USA, with 20 turbines generating 30 kW each.'),
            bullet('sm6-s2-b13', '1985: Vestas, a Danish company, emerges as a leader in wind turbine manufacturing, setting the stage for the modern wind industry.'),
            bullet('sm6-s2-b14', '1987: The UK\'s first commercial wind farm is established in Delabole, Cornwall.'),
            h3('sm6-s2-h10', '1990s: Scaling Up'),
            bullet('sm6-s2-b15', '1991: The world\'s first offshore wind farm is built in Vindeby, Denmark, signalling advancements in turbine technology and applications.'),
            bullet('sm6-s2-b16', '1996: The Global Wind Energy Council (GWEC) is established to promote wind power worldwide.'),
            bullet('sm6-s2-b17', '1998: Enercon introduces the first direct-drive turbine, eliminating the need for a gearbox and improving reliability.'),
            h3('sm6-s2-h11', '2000s: Technological Advancements'),
            bullet('sm6-s2-b18', '2001: Wind power surpasses 10 GW of global installed capacity, marking rapid growth.'),
            bullet('sm6-s2-b19', '2007: The European Wind Energy Association (EWEA) reports that wind power meets 3% of Europe\'s electricity demand.'),
            bullet('sm6-s2-b20', '2008: GE introduces the 2.5 MW turbine, setting new standards for utility-scale projects.'),
            h3('sm6-s2-h12', '2020s: Sustainability and Innovation'),
            bullet('sm6-s2-b21', '2020: Onshore wind becomes the largest renewable energy source globally, contributing significantly to decarbonisation goals. Advances in digital technologies, such as AI and IoT, improve turbine efficiency and predictive maintenance.'),
            bullet('sm6-s2-b22', '2021: The first 6 MW onshore wind turbines are installed, significantly increasing capacity per turbine and reducing land use intensity.'),
            bullet('sm6-s2-b23', '2022: Focus on sustainability intensifies, with the development of fully recyclable turbine blades. Major wind energy markets adopt stricter standards for environmental impact and turbine end-of-life management.'),
            bullet('sm6-s2-b24', '2023: Hybrid systems integrating onshore wind, solar, and battery storage gain traction, allowing for more reliable power generation and grid stability.'),
            bullet('sm6-s2-b25', '2024: Advanced materials and modular turbine designs reduce construction costs and time, making onshore wind more accessible for community-scale projects in remote areas.'),
          ],
        },
        onshoreWindCapacityChart,
      ],
    },

    // ── SECTION 3: Types of Wind Turbines (PDF pp. 13–15) ────────────────────
    {
      _id: 'sm6-sec-3-types',
      title: 'Types of Wind Turbines',
      slug: { _type: 'slug', current: 'onshore-wind-turbine-types' },
      estimatedMinutes: 10,
      content: [
        {
          _type: 'imageBlock',
          _key: 'sm6-s3-hero',
          image: localImage('Images/AdobeStock_1164688628.webp', 'Modern onshore wind turbines'),
          fullWidth: true,
        },
        {
          _type: 'richText',
          _key: 'sm6-s3-hawt',
          content: [
            h2('sm6-s3-h1', 'Horizontal-Axis Wind Turbines (HAWTs)'),
            p('sm6-s3-p1', 'HAWTs are the most widely used type of wind turbines, characterised by their rotor and blades rotating around a horizontal axis. The turbine\'s rotor faces the wind directly, either upwind or downwind, ensuring maximum energy capture. They are mounted on tall towers to access higher and more consistent wind speeds.'),
            h3('sm6-s3-h2', 'Key Features'),
            bullet('sm6-s3-b1', 'Orientation: Rotor faces the wind for optimal energy generation.'),
            bullet('sm6-s3-b2', 'Efficiency: High energy conversion efficiency due to advanced aerodynamic blade designs.'),
            bullet('sm6-s3-b3', 'Height: Installed on tall towers to leverage stronger winds.'),
            bullet('sm6-s3-b4', 'Applications: Utility-scale projects, providing the bulk of onshore wind energy globally.'),
            h3('sm6-s3-h3', 'Three Most Common Types of HAWTs'),
            bullet('sm6-s3-b5', 'Traditional Gearbox-Driven HAWTs: Use a gearbox to increase rotational speed from the blades to the generator. Common for large-scale wind farms but require regular maintenance.'),
            bullet('sm6-s3-b6', 'Low-Wind-Speed HAWTs: Designed with longer blades and optimised mechanics to operate efficiently in areas with weaker winds. Expand the viability of wind energy in inland or low-resource areas.'),
            bullet('sm6-s3-b7', 'Direct-Drive HAWTs: Eliminate the gearbox by connecting the rotor directly to the generator. Reduced mechanical complexity and improved reliability.'),
          ],
        },
        {
          _type: 'imageBlock',
          _key: 'sm6-s3-hawt-img',
          image: localImage('Images/AdobeStock_570873815.webp', 'Horizontal-axis wind turbines in a field'),
          caption: 'Horizontal-Axis Wind Turbines (HAWTs) — the dominant technology for utility-scale onshore wind energy.',
        },
        {
          _type: 'richText',
          _key: 'sm6-s3-vawt',
          content: [
            h2('sm6-s3-h4', 'Vertical-Axis Wind Turbines (VAWTs)'),
            p('sm6-s3-p2', 'VAWTs have a rotor that rotates around a vertical axis, allowing them to capture wind from any direction without needing to reorient. They are typically smaller and less efficient than HAWTs but are ideal for turbulent wind conditions and urban settings.'),
            h3('sm6-s3-h5', 'Key Features'),
            bullet('sm6-s3-b8', 'Orientation: Operates independently of wind direction.'),
            bullet('sm6-s3-b9', 'Maintenance: Easier to maintain due to ground-level components.'),
            bullet('sm6-s3-b10', 'Efficiency: Lower than HAWTs but suitable for specific conditions.'),
            bullet('sm6-s3-b11', 'Applications: Urban installations, small-scale projects, and areas with unpredictable winds.'),
            h3('sm6-s3-h6', 'Three Most Common Types of VAWTs'),
            bullet('sm6-s3-b12', 'H-Rotor Turbines: A variation of the Darrieus design with straight vertical blades. Simplifies construction and improves performance in variable winds.'),
            bullet('sm6-s3-b13', 'Savonius Turbines: Use scooped, barrel-shaped blades. Ideal for low-wind-speed applications but less efficient in high-speed winds.'),
            bullet('sm6-s3-b14', 'Darrieus Turbines: Feature curved blades, resembling an eggbeater. High efficiency in steady winds but require an external mechanism to start.'),
          ],
        },
        {
          _type: 'imageBlock',
          _key: 'sm6-s3-vawt-img',
          image: localImage('Images/AdobeStock_333530096.webp', 'Vertical-axis wind turbine'),
          caption: 'Vertical-Axis Wind Turbines (VAWTs) — suitable for urban and turbulent wind environments where omnidirectional capture is an advantage.',
        },
      ],
    },

    // ── SECTION 4: Location & Grid Integration (PDF pp. 15–17) ───────────────
    {
      _id: 'sm6-sec-4-location',
      title: 'Location, Layout & Grid Integration',
      slug: { _type: 'slug', current: 'onshore-wind-location-grid' },
      estimatedMinutes: 10,
      content: [
        {
          _type: 'imageBlock',
          _key: 'sm6-s4-hero',
          image: localImage('Images/AdobeStock_948897754.webp', 'Onshore wind farm aerial layout'),
          fullWidth: true,
        },
        {
          _type: 'richText',
          _key: 'sm6-s4-location',
          content: [
            h2('sm6-s4-h1', 'Wind Farm Location & Optimisation'),
            p('sm6-s4-p1', 'The layout and optimisation of onshore wind farms are crucial for maximising energy capture, minimising losses, and ensuring long-term operational efficiency. These processes involve strategic turbine placement, optimised spacing, and advanced technologies to enhance performance while balancing cost-effectiveness and environmental considerations.'),
            h3('sm6-s4-h2', 'Turbine Spacing and Placement'),
            bullet('sm6-s4-b1', 'Sufficient spacing is ensured between turbines to reduce wake effects, where turbulence caused by one turbine affects others downstream.'),
            bullet('sm6-s4-b2', 'Typical spacing involves 7–10 rotor diameters in the prevailing wind direction and 3–5 rotor diameters laterally to optimise energy output and land use.'),
            bullet('sm6-s4-b3', 'Turbines are aligned to face the prevailing wind direction for maximum energy capture.'),
            h3('sm6-s4-h3', 'Cluster Configurations'),
            bullet('sm6-s4-b4', 'Staggered layouts are used, such as checkerboard patterns, to minimise wind flow disruptions and improve energy generation efficiency.'),
            bullet('sm6-s4-b5', 'Avoiding linear rows unless dictated by land availability, as they are more susceptible to wake losses.'),
            h3('sm6-s4-h4', 'Computational Modelling'),
            bullet('sm6-s4-b6', 'Modelling such as Computational Fluid Dynamics (CFD) is used to simulate wind flow and interactions between turbines.'),
            bullet('sm6-s4-b7', 'Optimise turbine placement and overall wind farm design to maximise energy yield and minimise wake interference.'),
          ],
        },
        {
          _type: 'gridIntegrationDiagram' as const,
          _key: 'sm6-s4-grid-diagram',
          title: 'Onshore Wind — Grid Integration Flow',
          caption: 'How electricity travels from the wind farm through the transformer, high-voltage transmission lines, and grid substation to reach homes and industry.',
        },
        {
          _type: 'richText',
          _key: 'sm6-s4-grid',
          content: [
            h2('sm6-s4-h5', 'Grid Integration of Onshore Wind Energy'),
            p('sm6-s4-p2', 'Grid integration of onshore wind involves connecting wind farms to the electricity grid and ensuring their power is transmitted, distributed, and utilised effectively. This process involves several technical, operational, and infrastructure considerations to manage the variability of wind energy while maintaining grid stability.'),
            h3('sm6-s4-h6', 'Connection to the Grid'),
            bullet('sm6-s4-b8', 'Wind farms are connected to substations, which step up the voltage of the electricity generated by turbines to match the grid\'s requirements.'),
            bullet('sm6-s4-b9', 'High-voltage transmission lines carry electricity from wind farms to the main grid, often spanning long distances.'),
            h3('sm6-s4-h7', 'Power Conversion'),
            bullet('sm6-s4-b10', 'The electricity generated by wind turbines is alternating current (AC) but may need conversion to a specific frequency and voltage before integration with the grid.'),
            bullet('sm6-s4-b11', 'Power electronics, such as inverters and converters, are used to synchronise the electricity from the wind farm with grid standards.'),
            h3('sm6-s4-h8', 'Energy Storage Systems'),
            bullet('sm6-s4-b12', 'Batteries or other storage systems can be integrated to store excess wind energy and supply it during periods of low generation, smoothing variability.'),
            h3('sm6-s4-h9', 'Challenges of Grid Integration'),
            bullet('sm6-s4-b13', 'Intermittency: Wind energy is variable and depends on weather conditions, which can lead to fluctuations in electricity generation.'),
            bullet('sm6-s4-b14', 'Grid Stability: Large amounts of variable wind power can cause instability in the grid if not balanced with other generation sources or storage systems.'),
            bullet('sm6-s4-b15', 'Transmission Constraints: Onshore wind farms are often located in remote or rural areas far from demand centres, requiring significant investment in transmission infrastructure.'),
            bullet('sm6-s4-b16', 'Voltage and Frequency Regulation: Maintaining the grid\'s voltage and frequency becomes challenging as wind generation increases, necessitating advanced control systems.'),
          ],
        },
      ],
    },

    // ── SECTION 5: Financial Aspects (PDF pp. 18–22) ──────────────────────────
    {
      _id: 'sm6-sec-5-financial',
      title: 'Financial Aspects',
      slug: { _type: 'slug', current: 'onshore-wind-financial' },
      estimatedMinutes: 25,
      content: [
        {
          _type: 'richText',
          _key: 'sm6-s5-text',
          content: [
            h2('sm6-s5-h1', 'The Financial Outlook'),
            p('sm6-s5-p1', 'The financial viability of onshore wind energy projects is crucial for their global development and success. Economic considerations include upfront capital costs, operational expenses, revenue generation, and market dynamics that affect project profitability. In terms of cost analysis, onshore wind is subject to development expenditure (DevEx), capital expenditure (CapEx), and operational expenditure (OpEx). The overall cost-effectiveness is measured through the Levelised Cost of Energy (LCOE).'),
            h3('sm6-s5-h2', 'Development Expenditure (DevEx)'),
            p('sm6-s5-p2', 'DevEx refers to the costs incurred during the early stages of a wind project, before construction begins:'),
            bullet('sm6-s5-b1', 'Site Selection and Feasibility Studies: Wind resource assessments, meteorological studies, site surveys, environmental impact assessments, biodiversity studies, and grid connection feasibility analysis.'),
            bullet('sm6-s5-b2', 'Permitting and Regulatory Compliance: Costs for planning applications, zoning, permitting, public consultations, stakeholder engagement, and compliance with environmental, cultural, and legal requirements.'),
            bullet('sm6-s5-b3', 'Project Design and Engineering: Preliminary project layouts, engineering designs, logistical planning, technical modelling, wind flow analysis, and turbine optimisation.'),
            bullet('sm6-s5-b4', 'Financial and Legal Services: Costs for securing project financing, legal documentation, contracts, and due diligence for investors and lenders.'),
            bullet('sm6-s5-b5', 'Miscellaneous Pre-Construction Costs: Community benefit negotiations, local compensation agreements, land lease agreements, and upfront land acquisition costs.'),
            h3('sm6-s5-h3', 'Capital Expenditure (CapEx)'),
            p('sm6-s5-p3', 'CapEx refers to the upfront costs of building the wind farm and connecting it to the grid:'),
            bullet('sm6-s5-b6', 'Turbine Procurement: Costs of turbines, blades, towers, and associated equipment. Turbine procurement is the largest contributor to CapEx (65–85%).'),
            bullet('sm6-s5-b7', 'Installation and Construction: Site preparation, foundation laying, transportation and assembly of turbines.'),
            bullet('sm6-s5-b8', 'Grid Connection: Building substations, transformers, and transmission lines to connect the wind farm to the electricity grid.'),
            bullet('sm6-s5-b9', 'Infrastructure Development: Construction of access roads, crane paths, and on-site facilities such as control rooms and storage areas.'),
            bullet('sm6-s5-b10', 'Land Costs: Payments for land acquisition or leasing.'),
            bullet('sm6-s5-b10a', 'Permits and Licences: Final regulatory costs and environmental offsetting measures, if required.'),
            h3('sm6-s5-h4', 'Operational Expenditure (OpEx)'),
            p('sm6-s5-p4', 'OpEx refers to ongoing costs incurred during the operational phase of the wind farm:'),
            bullet('sm6-s5-b11', 'Maintenance and Repairs: Regular servicing of turbines and ancillary equipment, plus unscheduled repairs due to wear and tear or faults.'),
            bullet('sm6-s5-b12', 'Operational Management: Staffing costs including site managers and technicians, remote monitoring systems, and operational software.'),
            bullet('sm6-s5-b13', 'Land Rent and Royalties: Ongoing payments to landowners or host communities, and royalties for shared benefit or revenue-sharing agreements.'),
            bullet('sm6-s5-b14', 'Insurance and Taxes: Coverage for turbine damages, third-party liabilities, and business risks, plus compliance with local and national tax obligations.'),
            bullet('sm6-s5-b14a', 'Utilities and Consumables: Energy consumption for operational facilities and miscellaneous supplies for daily operations.'),
          ],
        },
        onshoreWindLcoeRangeChart,
        {
          _type: 'richText',
          _key: 'sm6-s5-lcoe-text',
          content: [
            h2('sm6-s5-h5', 'Levelised Cost of Energy (LCOE) in Onshore Wind'),
            p('sm6-s5-p5', 'The Levelised Cost of Energy (LCOE) is a key measure of the cost-effectiveness of onshore wind projects. It represents the average cost of building and operating a wind farm over its lifetime, divided by the total electricity generated.'),
            h3('sm6-s5-h6', 'Factors Affecting LCOE'),
            bullet('sm6-s5-b15', 'Capital Costs: Turbine procurement is the largest contributor to CapEx (65–85%). Costs for grid connection, construction, and site preparation also impact LCOE.'),
            bullet('sm6-s5-b16', 'Capacity Factor: A higher capacity factor (the percentage of time turbines generate electricity) leads to more electricity output and lowers LCOE.'),
            bullet('sm6-s5-b17', 'Turbine Efficiency: Larger, more efficient turbines generate more electricity, improving cost-effectiveness.'),
            bullet('sm6-s5-b18', 'Project Lifetime: Longer turbine lifespans (20–25 years) spread costs over more electricity generated, reducing LCOE.'),
            bullet('sm6-s5-b19', 'Technology and Innovation: Modern turbine designs, predictive maintenance, and digital optimisation contribute to lower LCOE.'),
            bullet('sm6-s5-b19a', 'Financing Costs: Lower interest rates and favourable financing terms reduce overall costs, significantly impacting the LCOE calculation.'),
            h3('sm6-s5-h7', 'Global Trends in LCOE'),
            bullet('sm6-s5-b20', 'Falling Costs: Onshore wind LCOE has dropped significantly in the last two decades, with global averages reaching £26/MWh in 2021, and some projects achieving even lower costs.'),
            bullet('sm6-s5-b21', 'Asia: China and India benefit from lower labour and material costs.'),
            bullet('sm6-s5-b22', 'Europe: Advanced technology offsets higher labour and land costs.'),
            bullet('sm6-s5-b23', 'North America: Favourable wind conditions and large-scale projects drive low LCOE.'),
            bullet('sm6-s5-b24', 'Emerging Markets: Africa and Latin America are seeing significant cost reductions due to increasing adoption and supply chain growth.'),
            p('sm6-s5-p6', 'Onshore wind is now one of the cheapest energy sources, often competing with or outperforming fossil fuels and solar power. Continuous cost reductions, driven by technological improvements and scale, are expected to continue — with costs projected to drop as low as £20–25/MWh by 2030.'),
          ],
        },
        onshoreWindLcoeChart,
        onshoreWindCountriesChart,
      ],
    },

    // ── SECTION 5b: Global Dispersion (PDF p. 21) ─────────────────────────────
    {
      _id: 'sm6-sec-5b-global',
      title: 'Global Dispersion of Onshore Wind',
      slug: { _type: 'slug', current: 'onshore-wind-global-dispersion' },
      estimatedMinutes: 5,
      content: [
        {
          _type: 'richText',
          _key: 'sm6-s5b-text',
          content: [
            h2('sm6-s5b-h1', 'Global Dispersion of Onshore Wind Energy'),
            p('sm6-s5b-p1', 'Onshore wind energy has grown into a truly global industry, with significant installed capacity spread across Asia, Europe, the Americas, and beyond. The following country snapshots illustrate the scale and diversity of the global onshore wind market as of 2023:'),
            h3('sm6-s5b-h2', 'China'),
            p('sm6-s5b-p2', 'As of 2023, China leads the world in onshore wind energy capacity, with approximately 404.6 gigawatts installed. China\'s dominance is driven by ambitious government targets, strong manufacturing capacity, and extensive policy support including feed-in tariffs and mandatory grid connections.'),
            h3('sm6-s5b-h3', 'United States'),
            p('sm6-s5b-p3', 'The United States ranks second globally, with nearly 148 gigawatts of onshore wind capacity as of 2023. Federal incentives such as the Production Tax Credit, combined with state-level Renewable Portfolio Standards, have driven rapid growth — particularly across the Great Plains and Texas.'),
            h3('sm6-s5b-h4', 'Germany'),
            p('sm6-s5b-p4', 'Germany stands as Europe\'s largest onshore wind energy producer, with a total capacity of 69.46 gigawatts in 2023. Germany\'s strong industrial base and Energiewende (energy transition) policy have made it a global leader in turbine manufacturing and deployment.'),
            h3('sm6-s5b-h5', 'India'),
            p('sm6-s5b-p5', 'India has maintained its position as the fifth-largest wind energy market, with an installed capacity of 44.74 gigawatts in 2023. Reverse auctions and accelerated depreciation benefits have attracted significant private investment in wind energy projects.'),
            h3('sm6-s5b-h6', 'Spain'),
            p('sm6-s5b-p6', 'Spain has an installed wind energy capacity of 30.22 gigawatts as of 2023, making it one of Europe\'s leading wind markets. Spain benefits from excellent wind resources along its Atlantic coast and in the interior plateau regions.'),
            h3('sm6-s5b-h7', 'United Kingdom'),
            p('sm6-s5b-p7', 'The UK has 15.4 GW of onshore wind capacity, with Scotland accounting for the largest share. While Scotland has benefited from strong policy support, deployment in England has faced delays due to planning restrictions, though these are increasingly being relaxed to meet net-zero targets.'),
            h3('sm6-s5b-h8', 'Australia'),
            p('sm6-s5b-p8', 'Australia has 11.3 GW of onshore wind capacity, mainly concentrated in South Australia and Victoria. There are ambitious targets to reach 14 GW by 2025, though grid challenges in remote areas continue to present integration difficulties.'),
          ],
        },
      ],
    },

    // ── SECTION 6: Policy & Frameworks (PDF pp. 22–24) ───────────────────────
    {
      _id: 'sm6-sec-6-policy',
      title: 'Policy & Regulatory Frameworks',
      slug: { _type: 'slug', current: 'onshore-wind-policy' },
      estimatedMinutes: 10,
      content: [
        {
          _type: 'imageBlock',
          _key: 'sm6-s6-hero',
          image: localImage('Images/AdobeStock_731501610.webp', 'Wind turbines in a rural landscape with policy context'),
          fullWidth: true,
        },
        {
          _type: 'richText',
          _key: 'sm6-s6-text',
          content: [
            h2('sm6-s6-h1', 'Global Policy and Regulations for Onshore Wind'),
            p('sm6-s6-p1', 'Onshore wind energy development is shaped by policies and regulations designed to promote investment, ensure environmental sustainability, and facilitate integration into electricity grids. These frameworks vary by region but share common goals of increasing renewable energy adoption and reducing greenhouse gas emissions.'),
            p('sm6-s6-p2', 'Many countries set renewable energy targets as part of their climate action plans, such as the Nationally Determined Contributions (NDCs) under the Paris Agreement. Others are bound by Renewable Portfolio Standards and are required to source a specific percentage of electricity from renewables, driving demand for onshore wind.'),
            p('sm6-s6-p3', 'Incentive mechanisms vary on a global level, ranging from Feed-in Tariffs (FiTs) that offer fixed payments for wind energy producers from government, ensuring stable revenue for developers over a set period, to tax credits and exemptions.'),
            h3('sm6-s6-h2', 'Regional Frameworks'),
            bullet('sm6-s6-b1', 'North America — USA: Federal incentives are currently in place like the Production Tax Credit, and state-level Renewable Portfolio Requirements drive wind energy growth.'),
            bullet('sm6-s6-b2', 'North America — Canada: Provincial programmes use a mix of auctions, feed-in tariffs, and renewable energy portfolio requirements.'),
            bullet('sm6-s6-b3', 'Europe — European Green Deal: Aims to achieve net zero by 2050. The Renewable Energy Directive sets binding renewable energy targets and encourages cross-border collaboration.'),
            bullet('sm6-s6-b4', 'Asia — China: Utilises feed-in tariffs, mandatory grid connections, and ambitious capacity targets, making it the world\'s largest wind energy market.'),
            bullet('sm6-s6-b5', 'Asia — India: Implements reverse auctions and accelerated depreciation benefits to attract investment in wind energy projects.'),
            bullet('sm6-s6-b6', 'Emerging Frameworks: Countries like South Africa and Brazil use auctions to attract private investment, supported by international funding agencies. Challenges include regulatory uncertainty and limited grid infrastructure.'),
            h3('sm6-s6-h3', 'Global Policy and Regulation Challenges'),
            bullet('sm6-s6-b7', 'Policy Uncertainty: Sudden changes in subsidies or incentives can deter investment and slow project development. Consistent, long-term policies are critical for investor confidence.'),
            bullet('sm6-s6-b8', 'Permitting Delays: Lengthy and complex approval processes can escalate costs and extend project timelines. Streamlined permitting frameworks are increasingly being adopted to address this.'),
            bullet('sm6-s6-b9', 'Community Acceptance: Public concerns about noise, visual impacts, and land use conflicts can lead to opposition. Policies promoting community engagement and benefit-sharing are essential to gain public support.'),
            bullet('sm6-s6-b10', 'Environmental Protection: Regulations often require mitigation measures to protect birds, bats, and other wildlife. Balancing renewable energy deployment with biodiversity conservation remains a key challenge.'),
            bullet('sm6-s6-b11', 'Grid Integration: Insufficient or outdated grid infrastructure can limit the ability to integrate new wind capacity. Policies supporting grid modernisation and smart technologies are vital for scaling wind energy.'),
          ],
        },
        {
          _type: 'imageBlock',
          _key: 'sm6-s6-policy-img',
          image: localImage('Images/AdobeStock_848907343.webp', 'Global onshore wind policy and regulation'),
          caption: 'Global policy frameworks for onshore wind — from the European Green Deal to China\'s feed-in tariffs and the US Production Tax Credit.',
        },
      ],
    },

    // ── SECTION 7: Social & Environmental (PDF pp. 25–26) ────────────────────
    {
      _id: 'sm6-sec-7-social-env',
      title: 'Social & Environmental Landscape',
      slug: { _type: 'slug', current: 'onshore-wind-social-environmental' },
      estimatedMinutes: 10,
      content: [
        {
          _type: 'imageBlock',
          _key: 'sm6-s7-hero',
          image: localImage('Images/AdobeStock_1165794534.webp', 'Wind turbines in a natural landscape'),
          fullWidth: true,
        },
        {
          _type: 'richText',
          _key: 'sm6-s7-text',
          content: [
            h2('sm6-s7-h1', 'Social & Environmental Landscape of Onshore Wind'),
            p('sm6-s7-p1', 'While onshore wind provides clean energy, its environmental impacts cannot be ignored.'),
            h3('sm6-s7-h1b', 'Social Considerations'),
            bullet('sm6-s7-bs1', 'Visual Impact: Visual impact is a frequent complaint, as turbines alter landscapes that communities are attached to. This has led to opposition in countries like the UK, where wind farm proposals in scenic or rural areas can generate significant local controversy.'),
            bullet('sm6-s7-bs2', 'Noise Pollution: Noise from turbine blades and mechanical operations is another concern for residents living close to wind farms. While modern turbines have become significantly quieter, setback distances and noise thresholds remain important regulatory considerations.'),
            bullet('sm6-s7-bs3', 'Health Concerns: In some regions, health concerns have been raised by communities near wind farms. However, scientific evidence largely dismisses claims of direct health impacts at standard setback distances, though ongoing research continues to monitor potential effects.'),
            bullet('sm6-s7-bs4', 'Grid Infrastructure Near Communities: The proximity of grid infrastructure — including substations and transmission lines — to villages and towns can create social tensions. In countries like India and South Africa, communities have raised concerns about land use conflicts and environmental impacts from supporting grid infrastructure.'),
            bullet('sm6-s7-bs5', 'Economic Opportunity: In other cases, wind farms bring significant economic opportunities. Community benefit funds, local employment during construction and operation, and landowner lease payments can generate meaningful income for rural areas, turning potential opponents into supporters.'),
            h3('sm6-s7-h2', 'Environmental Considerations'),
            bullet('sm6-s7-b1', 'Habitat Disruption: Occurs during the construction phase, particularly in forested or ecologically sensitive areas. For example, in Brazil, wind projects in biodiversity-rich regions have raised concerns about deforestation and wildlife displacement.'),
            bullet('sm6-s7-b2', 'Bird and Bat Mortality: Turbine blades can pose risks to flying species, particularly in migratory corridors. In Europe, where wind farms are expanding into less developed areas, mitigation strategies such as blade curtailment and radar systems are being implemented.'),
            bullet('sm6-s7-b3', 'Grid Infrastructure Impacts: Grid connections can have environmental consequences. In some regions, substations and transmission lines are built near villages, requiring land clearing and affecting local ecosystems. For example, in Kenya, the Lake Turkana Wind Project faced criticism for its infrastructure\'s environmental impact on local communities and wildlife habitats.'),
            p('sm6-s7-p2', 'However, advancements in grid technology and careful planning are helping to mitigate these effects.'),
            h3('sm6-s7-h3', 'Net Positive Assessment'),
            p('sm6-s7-p3', 'Despite social and environmental concerns, onshore wind remains a net positive energy source. It provides clean, renewable power, significantly reducing greenhouse gas emissions and dependence on fossil fuels. While challenges such as visual impact, habitat disruption, and grid infrastructure near villages need careful management, the overall benefits of onshore wind far outweigh these concerns.'),
          ],
        },
        {
          _type: 'imageBlock',
          _key: 'sm6-s7-env-img',
          image: localImage('Images/AdobeStock_922364293.webp', 'Wind turbines and local environment'),
          caption: 'Onshore wind and the environment — careful siting and mitigation measures help balance energy generation with biodiversity protection.',
        },
      ],
    },

    // ── SECTION 8: Future & Conclusion (PDF pp. 26–27) ───────────────────────
    {
      _id: 'sm6-sec-8-future',
      title: 'The Future of Onshore Wind',
      slug: { _type: 'slug', current: 'onshore-wind-future' },
      estimatedMinutes: 5,
      content: [
        onshoreWindRegionalInstallationsChart,
        {
          _type: 'richText',
          _key: 'sm6-s8-text',
          content: [
            h2('sm6-s8-h1', 'The Global Future of Onshore Wind Energy'),
            bullet('sm6-s8-b1', 'The future of onshore wind energy is poised to play a pivotal role in the global transition to clean, affordable, and secure energy. With advancements in technology, reductions in costs, and increasing focus on decarbonisation, onshore wind will continue to expand rapidly, delivering benefits in energy security and environmental sustainability.'),
            bullet('sm6-s8-b2', 'The global onshore wind market is expected to grow significantly over the next decade. The Global Wind Energy Council (GWEC) forecasts that annual onshore wind installations will rise steadily, driven by increasing energy demand, net-zero commitments, and policy support. Emerging markets in Asia, Africa, and Latin America will see the fastest growth as they harness their abundant wind resources and expand grid infrastructure.'),
            bullet('sm6-s8-b3', 'In developed markets like Europe, the United States, and Australia, repowering older wind farms with advanced, high-capacity turbines will improve efficiency and output.'),
            bullet('sm6-s8-b4', 'By 2030, onshore wind is expected to supply up to 30% of global electricity demand, contributing to energy diversification and decarbonisation.'),
          ],
        },
        onshoreWindForecastChart,
        {
          _type: 'richText',
          _key: 'sm6-s8-conclusion',
          content: [
            h2('sm6-s8-h2', 'Conclusion'),
            p('sm6-s8-p1', 'The future of onshore wind energy represents a critical cornerstone of the global transition to clean, affordable, and secure energy. Falling Levelised Cost of Energy (LCOE), driven by technological advancements, economies of scale, and efficiency improvements, has made onshore wind one of the cheapest energy sources globally, with costs projected to drop as low as £20–25/MWh by 2030.'),
            p('sm6-s8-p2', 'Onshore wind also plays a vital role in enhancing energy security and resilience, reducing reliance on imported fuels and mitigating energy price volatility. Countries with strong wind resources, such as China, the US, and parts of Europe, are using onshore wind to stabilise domestic supply while regions in Africa and Latin America are leveraging it to address energy poverty and improve grid resilience.'),
            p('sm6-s8-p3', 'From a sustainability perspective, onshore wind aligns perfectly with global net-zero goals by 2050. It produces no emissions during operation, significantly reduces greenhouse gases, and offers minimal environmental impact compared to fossil fuels. As the sector evolves, sustainable practices — such as recyclable turbine components, biodiversity protection, and hybrid renewable systems — will further strengthen its environmental credentials.'),
            p('sm6-s8-p4', 'While challenges remain, including social acceptance, habitat disruption, and grid integration, onshore wind\'s ability to deliver low-cost, clean, and reliable energy far outweighs these concerns. Its role in ensuring energy security, reducing emissions, and driving economic growth underscores its importance as a global solution for a sustainable and resilient energy future.'),
          ],
        },
        {
          _type: 'imageBlock',
          _key: 'sm6-s8-final-img',
          image: localImage('Images/AdobeStock_937557837.webp', 'Onshore wind farm at sunset — the future of clean energy'),
          caption: 'Onshore wind — a cornerstone of the global clean energy transition, powering millions of homes with zero operational emissions.',
        },
      ],
    },
    // ── CONCLUSION: Sub-Module Summary ────────────────────────────────────────
    {
      _id: 'sm6-sec-conclusion',
      title: 'Sub-Module Summary',
      slug: { _type: 'slug', current: 'onshore-wind-summary' },
      estimatedMinutes: 5,
      content: [
        {
          _type: 'richText',
          _key: 'sm6-conc-text',
          content: [
            h2('sm6-conc-h1', 'Sub-Module Summary'),
            p('sm6-conc-p1', 'This sub-module has examined onshore wind energy — the backbone of global renewable power — from its historical origins to its role as one of the most cost-competitive electricity sources available today. Onshore wind has evolved from small experimental turbines in Denmark and the USA during the 1970s and 80s into a mature, globalised industry. Horizontal Axis Wind Turbines (HAWTs) dominate commercial deployment, with rotor diameters now routinely exceeding 150 metres and hub heights surpassing 100 metres — capturing stronger, steadier winds at altitude.'),
            p('sm6-conc-p2', 'Site selection and grid integration are defining factors in project success. Wind resource mapping, turbine spacing (typically 3–5 rotor diameters apart), and proximity to existing transmission infrastructure all directly influence energy yield and economics. The Levelised Cost of Energy (LCOE) for onshore wind has fallen dramatically — projected to reach as low as £20–25/MWh by 2030 — making it among the cheapest forms of new electricity generation in most markets. China leads global installed capacity, followed by the USA and Germany, while emerging markets in Africa, India, and Latin America represent the fastest-growing frontier.'),
            p('sm6-conc-p3', 'Policy frameworks — from CfDs and renewable portfolio standards to tax incentives and permitting reform — remain essential for continued deployment at the pace required. Social acceptance, visual impact, noise, and biodiversity considerations all require active stakeholder engagement. Where communities are partners in development rather than passive recipients, projects proceed faster and generate lasting local economic benefit. Onshore wind\'s combination of low cost, proven technology, and rapid deployment time makes it indispensable to any credible net zero strategy.'),
          ],
        },
        {
          _type: 'calloutBlock',
          _key: 'sm6-conc-callout',
          variant: 'key-fact',
          title: 'End of Sub-Module 6',
          body: 'You now have a comprehensive understanding of onshore wind energy — its technology, economics, global distribution, policy environment, and future outlook. This sub-module, together with Fixed and Floating Offshore Wind, completes your grounding in wind energy as a whole.',
        },
      ],
    },
    {
      _id: 'sm6-sec-col',
      title: 'Confirmation of Learning',
      slug: { _type: 'slug', current: 'onshore-wind-confirmation' },
      estimatedMinutes: 15,
      content: [
        {
          _type: 'confirmationQuizBlock' as const,
          _key: 'sm6-col-quiz',
          subModuleSlug: 'onshore-wind',
          moduleId: 'module-1',
        },
      ],
    },

  ],
}
